##############################
## All - Builds All Alpine
##############################
.PHONY: all
all: defaults languages devops sdks

.PHONY: defaults
defaults:
	cd defaults && $(MAKE)

.PHONY: languages
languages:
	cd languages && $(MAKE)

.PHONY: devops
devops:
	cd devops && $(MAKE)

.PHONY: sdks
sdks:
	cd sdks && $(MAKE)


